### ISSUE TITLE
Few issues - undefined module and hanging promise

### ISSUE THREAD

**Issue by rockyhuber** [lodestreams/waveform-samples-generator#1]
Firstly  - npm install waveform-samples-generator
waveform-samples-generator doesn't exist when trying to uninstall.
When I do this "npm i @lodestream/waveform-samples-generator" it installs.

When I import @lodestream/waveform-samples-generator it imports.

When I execute the code as you specified, I get a hanging promise that doesn't seem to resolve:
Promise
  { adapter: { data: [Object] },
  segments: {},
  points: {},
  offset_start: 0,
  offset_end: 355,
  offset_length: 355 } }

Cant get your plugin to work properly.

**Comment by rankun203** [comment]
@rockyhuber Hello, sorry for the unclear README, I've updated them and added a Travis badge.

You could either look into the [test file](https://github.com/lodestreams/waveform-samples-generator/blob/master/src/parser.spec.ts) or follow the README again for instructions.

For that issue you mentioned above, since `max`, `min` etc are getters, lazily initialized, so you have to call on those properties to get the values out. I've updated the README code example for your convenience.
